# Generated by Django 5.2.12 on 2026-04-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobapplication_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(default='Not Specified', max_length=150),
        ),
    ]
